README.md

adding meta-data based on bioCADDIE DATS format.

adding preliminary meta-data format specification

---

.gitmodules

This PR:
* Adds Samir's multicenter phantom dataset, using the workflow from `conp-dataset`

[Dataset] Add samir phantom dataset

---

README.md

There are different possible ways of testing the addition of a dataset - I am documenting the one I used - if someone finds a better way please update.

Documenting how to test PR for adding datalad datasets

---

metadata/example/SDasDataset.json

added dimension
added few other details

improvement to SDas metadata file

---

metadata/example/simonDataset.json

adding SIMON metadata

---

.gitmodules

This PR:
* Adds the datalad dataset submodule of the visual working memory study from London, Ontario. Dataset taken from OpenNeuro

[Dataset] Add Visual Working Memory dataset from OpenNeuro

---

metadata/example/preventAD.json

ajouter citations,
retrait reference interlex_TBD
ajout extra-properties

added to preventAD metadata file

---

metadata/example/SDasDataset.json

also added link to phantom-dev.loris.ca

removed some invalid interlex link

---

.gitmodules

This PR updates the git submodules to their latest version

Updating Git Submodules

---

.gitmodules

This updates contain the new descriptor files for multicenter-phantom and prevent-ad

[Update] Update the submodules with the descriptor files

---

.gitmodules

PR:
- Adds datasets stored on OSF, processed in London, Ontario
- Big Brain Hippocampus Unfolding (BigBrainHippoUnfold) data 
- Accurate registration of the BigBrain dataset with the MNI PD25 and ICBM152 atlases (BigBrainMRICoreg)
- Human Connectome Project Diffusion FOD Template from 100 Unrelated Subjects (HCPUR100-Template)

[Dataset] Add datasets from the Khan Lab

---

README.md

Updating visual working memory submodule with origin and added instruction flow in README for Updating a Submodule
Mandatory files and elements before approval:
- A `README.md` file, at the root of the dataset
- A `dats.json` file, at the root of the dataset
- If configuration is required (for instance to enable a special remote), a `config.sh` script at the root of the dataset
- A DOI (see instructions in [contribution guide](https://github.com/CONP-PCNO/conp-dataset/blob/master/.github/CONTRIBUTING.md), and corresponding badge in `README.md`
Additional functional checks:
- Dataset can be installed using DataLad, recursively if it has sub-datasets
- Every data file has a URL
- Every data file can be retrieved or requires authentication
- `dats.json` is a valid DATs model 
-  If dataset …

Updating visual working memory conp submodule with origin

---

.gitmodules

This dataset includes 20 datalad links to repositories of zipped summary data from the BrainSpan Atlas of the Developing Human Brain, generated by the Allen Institute for Brain Science, covering developmental transcriptome data, normalised expression values for prenatal LMD microarrays, and 3-D fiber tract and developmental transcriptome sampling annotation at 8 developmental stages ranging from early embryonic to 32 years old.  It also includes a PDF of a white paper describing the normalisation process used in the developmental transcriptome dataset, and a CSV containing tissue sample metadata and URLs for downloading raw LMD microarray files.

Adding Brainspan dataset

---

.gitmodules

An update to existing dataset to include metadata.

[dataset] added DATS to khanlab datasets

---

.gitmodules

This PR replaces PR #94.
This update adds two new brain transcriptomics datasets. The Transcriptomic Atlas of Mouse Neocortical Layers dataset contains transcriptomes from seven different layers of mouse somatosensory cortex, with raw read data, layer enrichment probabilities for Ensembl and de novo genes and transcripts, and replications specific to dorsal and lateral cortex. The Allen Brain Atlas Cell Types dataset includes transcriptomic data from several subregions of human and mouse cortex, and comparative data from the thalamus of human, mouse and macaque.
This update also standardises the capitalisation of "DATS.json" for the SIMON, multicenter-phantom and visual-working-memory datasets, as a step towards passing Travis-CI tests.

Adding Transcriptomic Atlas of Mouse Neocortical Layers and Allen Brain Atlas Cell Types datasets

---

.gitmodules
scripts/crawl_zenodo.py

- Removed outdated PERFORM dataset (replaced by PERFORM_Dataset__one_control_subject)
- Script has less bugs when passing and retrieving stored tokens
- Script will now create a new branch and PR for every single dataset creation and update

Remove outdated PERFORM dataset and script improvements

---

.gitmodules

Removed the following datasets as they seem to be unmaintained tests:
* `investigators/jb` (to be confirmed by @jbpoline)
* `investigators/Park-Patrick` (checked with @Park-Patrick)
No new dataset, checklist isn't relevant.
We should now be green in Travis!

Removed Patrick's and JB's datasets

---

.gitmodules

This PR adds DATS.json-ld files, generated from the DATS.json files, for seven of the CONP datasets (1000GenomesProject, Brainspan, PERFORM, celltypes, mm_neo_atlas, nhpatlas and refseq) and also removes the obsolete descriptor.json file from the PERFORM dataset.  These files have been generated mostly automatically, though some manual intervention is needed in cases of ambiguity (eg, for some of these datasets, the "authors" or "creators" entries are lists of names and count as a People entity in DATS, while for others where a consortium is listed as author that counts as an Organization entity.)

Adding DATS.json-ld files

---

.gitmodules

Datasets from the OpenPain project: http://openpain.org

Added 6 OpenPain datasets

---

.github/PULL_REQUEST_TEMPLATE.md

Capitalized DATS.json in PR template.

Capitalized DATS.json

---

scripts/crawl_zenodo.py
scripts/crawl_zenodo.sh

Few small improvements to logging, functionality and exception handling:
- Now logs when it is creating a PR
- Each crawling section is now delimited by ************ section *************** in the logs
- Adds the `title` field when creating the DATS.json
- When updating a dataset, it will pull from the remote first before updating
- Added try and catch all exceptions for entire crawler

Zenodo crawler improvements

---

.gitmodules

This is a DataLad dataset for the BigBrain. Linking files stored on the MNI's FTP server.

BigBrain dataset

---

.gitmodules

This PR removes the submodules for the three datasets under _investigators/Khanlab_ and replaces them with submodules under _projects/Khanlab_, pointing to new forks in _conpdatasets_. The investigators directory  It also updates two of the links in the _refseq_ dataset to newer versions of the relevant files; this has been done manually as a temporary measure prior to developing a method to automatically update that dataset.

Merge Khanlab datasets into projects

---

.gitmodules

This is to fix [ERROR] Failed to clone from all attempted sources occuring for khanlab submodules

fix khanlab submodules url

---

scripts/crawl_zenodo.py

Zenodo generated DATS.json now correctly contains file types/modalities of the dataset

Zenodo crawler dataset file types implementation in DATS

---

.gitmodules
scripts/crawl_zenodo.py

This PR is to correct a number of typos in the "description" and "types" fields for the preventad-open and multicenter-phantom datasets.

Correcting typos in description, types fields

---

.travis.yml
scripts/crawl_zenodo.py
tests/test_zenodo_crawler.py

Changed the generation of DATS.json file such that:
- The dataset size is in a human-readable format.
- The distributions authorizations is inferred from Zenodo access right.

Enhancements to Zenodo crawler

---

scripts/dats_validator/examples/valid_dats.json

Updated submodule containing DATS schemas with conp custom changes to the list of the required fields.

Updates in DATS schema

---

.gitmodules

This PR updates the 1000Genomes Project dataset. replacing links that were broken by a change of directory structure at the source ftp site, and adding 9 small supplementary files.

Updating 1000GenomesProject dataset

---

.gitignore
scripts/Crawlers/OSFCrawler.py
scripts/crawl.py
scripts/crawl.sh
tests/test_osf_crawler.py

- Add OSF platform crawler
- Does not support public/restricted datasets yet

Implement OSF crawler

---

README.md

Recrawled SIMON dataset. As a result:
* Data files are now on http://amnesia.cbrain.mcgill.ca
* Data files can be downloaded individually rather than through a single zip archive.
#21 #15

Recrawled SIMON dataset

---

.gitmodules

This PR carries out the following updates:
1) Updates Prevent-AD DATS.json to correct the URL showing in the portal.
2) Adds the BigBrain logo to BigBrain_3DSurfaces and BigBrain_3DClassifiedVolumes
3) Correctly synchronises the SIMON data.

updating submodules and logos

---

scripts/Crawlers/ZenodoCrawler.py

While making changes to the configuration file in #257 I broke the Zenodo crawler.
This change fixes the problem introduced.
#257 introduced this bug

[FIX] broken path to config file.

---

scripts/Crawlers/BaseCrawler.py
scripts/Crawlers/ZenodoCrawler.py

- In BaseCrawler, fixes bug which didn't use clean title to know which branch it is pushing to
- In ZenodoCrawler, getting readme content is now properly indented
- In ZenodoCrawler, annex-ignores "config" as per #257 renaming of "unlock.py" to "config"

Crawler bug fixes

---

.circleci/config.yml
.circleci/images/Dockerfile
.gitmodules
.travis.yml
scripts/Crawlers/BaseCrawler.py
scripts/Crawlers/ZenodoCrawler.py
scripts/unlock.py
tests/create_tests.py
tests/functions.py

This PR does the following:
1) Updates the derived datasets BigBrain_3DClassifiedVolumes and BigBrain_3DSurfaces to contain links to the source BigBrain dataset in accordance with YODA principles, and also adds appropriate values to  `extraProperties->derivedFrom` in the DATS.json for these derived datasets.
2) adds the value "Principal Investigator" under `roles` attached to the appropriate name under `creators` for multicenter-phantom, visual-working-memory and the three Khanlab datasets.

updating DATS.json for derived datasets, PI role

---

.github/ISSUE_TEMPLATE/dataset-error.md

The proposed change is to add an issue template to report problem when installing a dataset.

Template for broken dataset.

---

tests/README.md

This changes aims at providing the currently missing documentation for the dataset monitoring system.
Any feedback would be appreciated.
#259 Implementations of the monitoring system
#298 Current documentations

[ADD] Documentation for the monitoring system.

---

tests/functions.py

Currently, datasets with sub-modules fail to the test suite; see BigBrain_3DSurfaces in [logs](https://app.circleci.com/pipelines/github/CONP-PCNO/conp-dataset/174/workflows/ba6f0578-c707-46d5-a7d1-9aa5b53549bc/jobs/322) as an example.
This is due to a bug in the handling of datasets with sub-modules. The path to the sub-modules are appended twice thus the sub-modules files are not found during the download.
Those changes fix this issue.

[FIX] Dataset with submodule failed to downoad

---

README.md

The current `README.md` has a broken link for the test documentation.

[FIX] Broken link to test suite documentation.

---

tests/template.py

The current implementation for downloading files in the test suite works for restricted dataset on Zenodo, however, it does not consider the failure of other types of dataset.
This can lead to the test suite timing out when an authenticated dataset is trying to authenticate with eh wrong credentials, or there is an error on the server side.
To prevent this from happening, the extra steps required for downloading restricted Zenodo dataset is now only executed for those. It also has a time limit to execute that step which after will continue with the remaining of the test.

[FIX] previous handling of restricted Zenodo dataset led to timeouts.

---

.gitmodules

This PR updates the `preventad-open` dataset to the latest commit and adds the `preventad-open-bids` dataset to the super dataset.
https://github.com/CONP-PCNO/conp-dataset/issues/325
https://github.com/CONP-PCNO/conp-dataset/issues/278

Update preventad-open dataset and add preventad-open-bids dataset

---

.gitmodules

This is the third dataset to be added from OBI.
#353

Add Braincode NDD Priority Setting Partnership dataset

---

.gitmodules

This PR updates conp-dataset with the following submodule changes:
- redirect Reusing-Neuro-Data to point at conpdatasets rather than @gi114's personal repository
- redirect 1000GenomesProject to point at conpdatasets rather than @emmetaobrien's personal repository
- update refseq_Homo_sapiens for an updated genome annotation file
- update cneuromod to include `extraProperties->origin_*` fields in DATS.json as specified in https://github.com/CONP-PCNO/conp-dataset/issues/370

Updates to incorporate changes and fixes in submodules

---

scripts/Crawlers/OSFCrawler.py

- It now handles multiple pages of data
- It looks for root folder to download files from in case the dataset is nested in another one

OSF Crawler improvements

---

.gitmodules

This PR corrects an error in `.gitmodules` to address https://github.com/CONP-PCNO/conp-dataset/issues/409.

correcting format error in Reusing-Neuro-Data update

---

.gitmodules

This PR updates the link to the HCPUR100-Template dataset for updates in the original source.

updating link to corrected Khanlab/HCPUR100-Template dataset

---

tests/functions.py

This fixes small typos in the exception handling present in the `is_authentication_required` function of the `tests/function.py` file.

Fix typo in exception handling in is_authentication_required of tests/function.py

---

.gitmodules

This updates the date types and repository link of cneuromod to conpdatasets repo instead of glatard
#499 #454

Update cneuromod DATS.json date types and repository link to conpdatasets instead of glatard

---

.gitmodules

This PR updates the privacy field across subdatasets (except for those generated by crawlers) for compatibility with the standard format described in https://github.com/CONP-PCNO/conp-dataset/issues/536.

Updates to privacy field in DATS.json

---

.gitmodules

This PR updates the links to the `BigBrain_3DClassifiedVolumes`, `BigBrain_3DSurfaces,` and `mcgill-emc-rna-seq-experiments `datasets to point to forks under `conpdatasets`.

updating submodule links for datasets in personal git repositories.

---

.github/CONTRIBUTING.md
README.md

Remove the documentation referring to the `investigators` folder as it is no longer exists.

[UPDATE] Documentation with the current structure for datasets.

---

.gitmodules

BigBrain_Surface_Parcellations: [ADD] crawled dataset.

---

.gitmodules

BigBrain_BigBrainWarp_Support: [ADD] crawled dataset.

---

.gitmodules

BigBrain_Hippocampus_Segmentation: [ADD] crawled dataset.

---

.gitmodules

BigBrain_A3D: [ADD] crawled dataset.

---

.gitmodules

BigBrain_MRISIM: [ADD] crawled dataset.

---

scripts/datalad_crawlers/ftp_crawler.py

When there was an "[Err 104] Connection reset by peer" the script was hanging.
Also improved the overall performance and use git api instead of OS call.

[FIX] [REFACTOR] FTP crawler

---

scripts/auto_archive.py

This PR fixes two issues:
1. Datasets crawled from Zenodo and OSF were skipped during the archiving.
2. Datasets in sub-folder failed to be archived.
Fix #672

Fix auto-archive script

---

.github/workflows/update-submodules.yml

This PR propose a new GitHub workflow that automatically create a PR when a new version of a submodule is detected.
Example PR: https://github.com/mathdugre/submodule-update/pull/2.

[ADD] new workflow to automatically update submodules.

---

.gitmodules

This PR adds the BigBrain Raw Data to CONP.

[ADD] BigBrain Raw Data datasets.

---

.gitmodules

This PR adds the BigBrain Layer Segmentation derivate dataset to CONP.

[ADD] BigBrain Layer Segmentation derivate

---

.gitmodules

This PR adds the `microstructure_informed_connectomics` dataset

Adding microstructure_informed_connectomics dataset

---

scripts/auto_archive.py

This modifies the default behaviour of the auto-archive script since we will not be restricting anymore the size of downloadable archives as discussed during last week's developer meeting.

Update auto archive script with no default min size

---

.gitmodules

This PR adds the Taowu and Neurocon PD data to CONP.
**Please note** 
I have added the modifications recommended by Patrick Bermudez. However, I could not obtain the REB number from the authors of the dataset. The information regarding ethics can be found in the [paper](https://doi.org/10.1371/journal.pone.0188196) of the data publication.

Parkinson's disease MRI dataset | Taowu + Neurocon

---

.gitmodules

This PR updates the Neurocon and Taowu datasets to point at forks in `conpdatasets` rather than the original locations, and adjusts the titles to distinguish the two datasets in the CONP portal.

Update Neurocon and Taowu datasets

---

.pre-commit-config.yaml
scripts/auto_archive.py
scripts/dats_validator/validator.py

Should hopefully resolve the lint issue we have with new PRs lately.

Update version of black in precommit

---

.github/workflows/docker_build.yml

Replaces #760 sent by dependabot

Redo PR #760 that needed to be rebased to pass the tests

---

.github/workflows/stale.yml

Redo #762 that failed the tests and needed to be rebased

---

tests/template.py

This updates the BigBrain dataset to add the ARK ID to the DATS file now that it has been generated by the portal.

Update bigbrain to add ARK ID

---

.gitmodules

This pull request adds initial datasets including DATS.json files for five new braincode datasets.

Add the 5 braincode datasets without the other new datasets

---

tests/functions.py

This updates the authentication function used in testing to check whether there is any annexed content, and ignores the lack of auth info if there is not.

Update auth test to handle no annexed content

---

.gitmodules

This PR corrects an error in #813  where the new datasets were added at the wrong level in the directory structure.

correcting error in #813

---

scripts/DATS2csv/DATS2csv.pl

A minor update to #821 that fixes the perl script failing the linter

Trim whitespace in DATS2csv

---

.gitmodules

This PR updates the `refseq_Mus_musculus` dataset again as the source dataset updated twice in quick succession.

refseq_Mus_musculus update

---

.gitmodules

This PR adds updates to README.md and DATS.json for cneuromod and cneuromod.processed datasets to inform users of their alpha status.

Updating README and DATS.json files for cneuromod datasets: alpha flag

---

.gitmodules

This PR adds the Adolescent Brain Development dataset from the Lebel lab.

adding Lebel lab adolescent brain development dataset

---

scripts/sftp-crawler.pl

This PR replaces the contents of the Adolescent Brain Development dataset with a fresh ingestion of the data provided by the source lab on Nov 3 2023.  It also adds a progress indicator to the data ingestion script.

updating AdolescentBrainDevelopment with new ingestion from data provider.

---

scripts/Crawlers/BaseCrawler.py
scripts/Crawlers/OSFCrawler.py
scripts/crawl.py
scripts/crawl.sh

Fix various issues for the OSF Importer to sucessfully run.

[Crawler] Fix OSF importer

---

.gitmodules

This PR adds the following datasets to the CONP portal:
cneuromod (should be fully functional)
cneuromod.processed (some subdirectories still giving malformed URL issues, presenting for further testing)
cbig-parkinsons (contains dataset but not DATS.json or README)
cbig-als (contains DATS.json and README but no other data)

Adding cbig, cneuromod(test) datasets.

---

.gitmodules

This PR updates the cneuromod and cneuromod.processed datasets with the corrections to the templateflow submodule data structure made at the source lab, correcting an error with malformed download URLs.

Update for corrected version of cneuromod.processed

---

.gitmodules

This PR updates the Adolescent Brain Development dataset, which has been reingested to address strange download errors.

Updating AdolescentBrainDevelopment dataset

---

.gitmodules

This PR returns the appropriate logo to the AdolescentBrainDevelopment dataset, from which it was accidentally removed.

Restore logo to AdolescentBrainDevelopment

---

.gitmodules

This pull request adds a basic version of the CIMA-Q dataset containing README, DATS.json and logo.

adding CIMA-Q dataset

---

.gitmodules

This pull request adds the EEGnet Face13 dataset from @christinerogers.

adding eegnet_face13

---

.gitmodules

This PR adds the eegnet_wmt dataset to conp-datasets.  The PR has been submitted to allow automatic verification of the DATS file and the PR is not confirmed ready to merge at this time.

adding eegnet_wmt dataset

---

.gitmodules

This PR adds five new datasets:
`eegnet_aud`
`eegnet_tse`
`eegnet_vis`
`eegnet_lxn`
`eegnet_mfa`
and also updates the authorisation for the `landingPage` field in `eegnet_wmt` and `eegnet_face13` from "private" to "registered".

Adding new EEGnet datasets

---

.gitmodules

This PR adds two new datasets, `cbig_congenital_hypopituitarism_wes` and `cbig_catatonic_schizophrenia_wgs`, each containing a README and a DATS.json.  These datasets are test cases for a set of 40+ datasets of this type submitted from the source lab.

Adding two new cbig datasets, test cases for larger group of datasets

---

.gitmodules

This PR adds nine new whole genome datasets from CBIG:
```
cbig_essential_tremor_wgs
cbig_hereditary_spastic_paraplegia_wgs
cbig_moyamoya_wgs
cbig_primary_lateral_sclerosis_wgs
cbig_progressive_supranuclear_palsy_wgs
cbig_radiation_exposure_wgs
cbig_restless_legs_syndrome_wgs 
cbig_savant_syndrome_wgs 
cbig_schizophrenia_wgs
```

adding 9 new CBIG whole genome sequence datasets

---

.gitmodules

```
cbig_3_hydroxybutyric_aciduria_wes
cbig_adolescent_idiopathic_scoliosis_wes
cbig_alzheimers_disease_wes
cbig_amusia_wes
cbig_amyotrophic_lateral_sclerosis_wes
cbig_aneurysm_wes
cbig_arteriovenous_malformation_wes
cbig_autism_spectrum_disorder_wes
```

Adding 8 more CBIG whole exome sequence datasets

---

.gitmodules

```
cbig_bipolar_affective_disorder_wes
cbig_bipolar_ii_wes 
cbig_cerebellar_dysgenesis_wes 
cbig_cerebellar_hypoplasia_wes
cbig_chiari_type_i_malformation_wes
cbig_cluster_headache_syndrome_wes
cbig_congenital_anteriolateral_bowing_tibia_wes 
cbig_congenital_insensitivity_to_pain_wes
```

8 more new CBIG whole exome sequence datasets, batch 2 of 8

---

.gitmodules

This PR adds eight more new CBIG datasets:
```
cbig_congenital_malformations_nervous_system_wes
cbig_congenital_malformations_wes
cbig_crane_heise_syndrome_wes
cbig_disturbance_activity_attention_wes
cbig_DOOR_syndrome_wes
cbig_dysosteosclerosis_wes
cbig_dystonia_wes
cbig_ehlers_danlos_syndrome_wes
```
It also updates `cbig_congenital_anteriolateral_bowing_tibia_wes` to display the logo correctly.

add CBIG datasets, batch 3 of 8

---

.gitmodules

This PR adds the following 8 datasets:
```
cbig_epilepsy_wes
cbig_essential_tremor_wes
cbig_frontotemporal_dementia_wes
cbig_genitopatellar_syndrome_wes
cbig_glioma_wes
cbig_guam_als_pld_wes
cbig_hereditary_ataxia_wes
cbig_hereditary_spastic_paraplegia_wes
```

adding more CBIG whole exome sequence datasets, batch 4 of 8

---

.gitmodules

```
cbig_meningioma_wes
cbig_microcephaly_wes
cbig_mirror_movements_wes
cbig_neural_tube_defect_wes
cbig_nonsyndromic_intellectual_disability_wes
cbig_obsessive_compulsive_disorder_wes
cbig_osteoporosis_wes
cbig_other_congenital_brain_malformations_wes
```

adding CBIG whole exome sequence datasets, batch 6 of 8

---

.gitmodules

```
cbig_pervasive_developmental_disorder_wes
cbig_pontocerebellar_hypoplasia_wes
cbig_population_controls_wes
cbig_primary_lateral_sclerosis_wes
cbig_recurrent_depressive_disorder_wes
cbig_restless_legs_syndrome_wes
cbig_rothmund_thompson_syndrome_wes
cbig_savant_syndrome_wes
````

add CBIG whole exome datasets, batch 7 of 8

---

.gitmodules

```
cbig_schizencephaly_wes
cbig_schizoaffective_disorders_wes
cbig_schizophrenia_wes
cbig_scoliosis_wes
cbig_syndromic_intellectual_disability_wes
cbig_synesthesia_wes
cbig_yunis_varon_syndrome_wes
cbig_zimmerman_laband_syndrome_wes
```

adding CBIG whole exome sequences, batch 8 of 8

---

tests/test_minimal_tests.py

Remove a suspicious line as part of an investigation to fix a problematic test.

open-pain test fix

---

.gitmodules

This PR removes the `cneuromod.processed` dataset and adds the same dataset renamed to `cneuromod_processed` in order to address a CircleCI test failure.

Changing cneuromod.processed to cneuromod_processed

---

.gitmodules

This PR removes a misplaced comma from the DATS.json file in the eegnet_mfa dataset, which was not seen to be caught by the validator but prevented the dataset from displaying in the portal.

correcting JSON format error in DATS.json for eegnet_mfa

---

.gitmodules

Removing the dataset added by https://github.com/CONP-PCNO/conp-dataset/pull/923/ as it showed the same malformed structure as https://github.com/CONP-PCNO/conp-dataset/pull/927.

removed MICA_PNI dataset

---

.gitmodules

This PR manually adds the Quantitative T1 MRI dataset retrieved from zenodo by conp-bot for test purposes.

Manual addition of conp-bot Zenodo dataset [test]

---

.gitmodules

This PR removes submodules `eegnet_aud`, `eegnet_vis` and `eegnet_wmt` from conp-dataset prior to re-loading renamed versions.

Removing three EEGnet datasets prior to renaming

---

.gitmodules

This PR adds three renamed EEGnet datasets:
`eegnet_ips` (formerly `eegnet_aud`)
`eegnet_rvs` (formerly `eegnet_vis`)
`eegnet_tdw` (formerly `eegnet_wmt`)

adding back three renamed EEGnet modules

---

.gitmodules

`eegnet_mwa`
`eegnet_ssa`
`eegnet_ssm`
and also incorporates some updates to `eegnet_tse`.

Adding three new eegnet datasets, and one more update.

---

.gitmodules

This PR adds a version of `eegnet_mwa` with the most recently corrected `DATS.json` to `conp-dataset`.

re-adding eegnet_mwa

---

.gitmodules

This PR adds the dataset for Algonauts competitors from the CNeuromod project.

Adding Algonauts dataset
