README.md

implementing JB's remark about type.  Left indentation so it is easier to read for a human.

correction to `type` data in example

---

metadata/example/1KGP_chr1.json
metadata/example/1KGP_chr10.json
metadata/example/1KGP_chr11.json
metadata/example/1KGP_chr12.json
metadata/example/1KGP_chr13.json
metadata/example/1KGP_chr14.json
metadata/example/1KGP_chr15.json
metadata/example/1KGP_chr16.json
metadata/example/1KGP_chr17.json
metadata/example/1KGP_chr18.json
metadata/example/1KGP_chr19.json
metadata/example/1KGP_chr2.json
metadata/example/1KGP_chr20.json
metadata/example/1KGP_chr21.json
metadata/example/1KGP_chr22.json
metadata/example/1KGP_chr3.json
metadata/example/1KGP_chr4.json
metadata/example/1KGP_chr5.json
metadata/example/1KGP_chr6.json
metadata/example/1KGP_chr7.json
metadata/example/1KGP_chr8.json
metadata/example/1KGP_chr9.json
metadata/example/1KGP_chrMT.json
metadata/example/1KGP_chrX.json
metadata/example/1KGP_chrY.json
metadata/example/1KGP_master.json

This update adds 26 files of metadata for 1000 Genomes Project data provided by David Bujold at C3G, which document variation between 1093 human genome sequences.   One of these is a master file, and 25 contain metadata for individual chromosomes (1-22, X, Y, and the mitochondrial genome).  File structure has been validated against the DATS dataset_schema.json file from the bioCADDIE GitHub repository.  The metadata for each individual chromosome include names, file creation dates, locations for the zipped .vcf file containing the underlying data,  summary statistics of the single-nucleotide polymorphisms and insertion/deletion events recorded in each .vcf file, and  an "extraProperties" entry providing a link to the reference sequence for each chromosome.  The master file includes a …

example genomics metadata

---

.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
README.md

This PR improves our community guidelines based on [GitHub's suggestions](https://github.com/CONP-PCNO/conp-dataset/community). More specifically, it adds:
* A code of conduct, identical to [the one in conp-portal](https://github.com/CONP-PCNO/conp-portal/blob/master/.github/CODE_OF_CONDUCT.md).
* A contribution guide, describing how to add a dataset, including the forking and PR procedure. The corresponding instructions in README.md have been updated accordingly. README.md now focuses on instructions on how to use the dataset.
* Issue templates, identical to the ones in conp-portal.
A PR template was already proposed in #50. Licensing will be discussed in a separate issue.

Improving community guidelines

---

.github/CONTRIBUTING.md

Made a few changes to the documentation, as well as some suggestions based on the CONTRIBUTING document and from a previous attempt at adding a dataset (might be better fitted to create issues for them?). 
- Added a missing word to instructions under "Contribution workflow" heading
- Fix spacing under "Adding meta-data" heading
- Update URL to `metadata/example`
- Previous URL did not work - not sure if this was intent until metadata is formalized
- Intended audience for the document, and what is there experience?
- Maybe move the suggestion about reading GitHub documentation prior to the workflow heading (since there appears to be an underlying assumption of knowing how to use git. 
- Where should a user go / who to contact if there is an issue - post under issues in the repo? Would have …

Documentation fixes and suggestions

---

.github/CONTRIBUTING.md
README.md

This PR modifies the contribution guide as follows:
* Added new instructions on how to get a DOI for a dataset, following discussion at the dev meeting today
* Instructions on how to get help, following @kaitj suggestion in #57 
* Moved up instructions on how to use git and github, following @kaitj suggestion in #57 
* Integrated metadata instructions to "Add data" workflow, mentioned the need for a `dats.json` file
* Fixed broken link in `README.md`
Irrelevant here, this is not a new dataset.
#57

Improvements to contribution guide

---

.github/auto_assign.yml
README.md

This adds `auto-assign` to the repo, following this morning's discussion and suggestion by @edickie. This config should auto assign 2 random reviewers to any pull request, chosen in the following list:
- @jbpoline
- @paiva
- @edickie
- @glatard
- @dlq
- @PapillonMcGill
- @shots47s

Added auto assign, fixed link in README

---

scripts/crawl_zenodo.py

Instead of going through the complex procedure of uploading a dataset themselves, the dataset owners can now upload their dataset onto Zenodo with the keyword `canadian-open-neuroscience-platform` and this script will automatically fetch new changes and versions and create a pull request to this repository.
The procedure is as follows:
1. Make sure you have an up to date repository by pulling
2. Retrieve all current conp-dataset information stored in dats.json files (concept_doi and version_doi)
3. Retrieve all metadata for all zenodo datasets containing the keyword `canadian-open-neuroscience-platform`
4. Looping through the retrieved zenodo datasets metadata:
1. If zenodo dataset is existing in a conp-dataset by comparing concept_doi:
1. If the conp-dataset version is not current by …

Add zenodo crawler script (in progress)

---

tests/functions.py

Currently, some dataset tests are failing due to hanging authentication.
I think that timing out the request should solve that issue.
The timeout prevents two things: (1) hanging prompt for authentication and (2) full download of the data. (1) Prevent tests to fail when credentials are not provided while (2) aims at improving speed.
This PR should solve the authentication hanging issue with PR #82, #84, #86.

[Test function] Timeout download and hanging authentication

---

tests/create_tests.py
tests/functions.py

Instead of assuming every directory under "projects" or "investigators" is a dataset, get dataset paths from submodules.path instead from the .gitmodules file. Update tests to reflect the changes.
IMPORTANT: making tests enforce specifically "DATS.json" and "README.md" as written!!!!
#92

Make tests check submodules, not directories

---

.travis.yml
tests/test_zenodo_crawler.py

Fix zenodo crawler tests failing
Added `|| true` to `datalad install -r .` because installing Park-Patrick dataset causes that command and the entire travis build to crash:
Possible alternative: 
- Remove Park-Patrick dataset

fix zenodo crawler tests failing

---

.github/auto_assign.yml

Removed @paiva and @shots47s from the list of PR reviewers. Added @xlecours and @emmetaobrien.

Updated PR reviewers

---

.github/auto_assign.yml
.gitignore
.gitmodules
.travis.yml
scripts/dats_validator/README.md
scripts/dats_validator/examples/invalid_dats.json
scripts/dats_validator/examples/valid_dats.json
scripts/dats_validator/requirements.txt
scripts/dats_validator/validator.py
tests/create_tests.py
tests/functions.py
tests/test_dats_validator.py

This PR adds one additional field to DATS.json for 10 of the datasets in CONP (1000GenomesProject, Brainspan, celltypes, mm_neo_atlas, multicenter-phantom, nhpatlas, preventad-open, refseq, SIMON-dataset and visual-working-memory), *extra_properties->CONP_status*, to indicate which category the dataset should be labelled as in the CONP portal.   Valid values are "CONP", "Canadian" or "external".  Equivalent values have been independently added to the six openpain datasets in separate PRs.
~~The values included are reasonable best estimates based on other metadata, and are not meant to be final.  The purpose of submitting this PR before receiving final confirmed values is to have the data structure in place so that front-end development can proceed; the expected outcome is that it should …

Adding CONP_status to DATS.json

---

.gitmodules

This PR does the following:
- removes the logo from the celltypes dataset, which is not working.
- replaces the logo for the nhpatlas dataset, which is not legible on a white background, with the NCBI logo used in the refseq dataset
- updates the three Khan lab datasets under CONP-PCNO/investigators to point to forks with updated DATS.json as per https://github.com/CONP-PCNO/conp-dataset/pull/149 and https://github.com/CONP-PCNO/conp-dataset/pull/125

Logo tidying and temporary redirect for Khan lab datasets.

---

.gitmodules

This PR updates submodule links for openpain repositories to now point to forks of those under conpdatasets.  Two of these, placebo_1 and cbp_resting, have had DATS.json updated to correct failure to display correctly in the CONP portal.

Update submodule links for openpain repositories

---

.travis.yml
scripts/crawl_zenodo.py
scripts/crawl_zenodo.sh
tests/test_zenodo_crawler.py

- Generated DATS.json now correctly displays total size and possible file formats
- Generated DATS.json contains zenodo logo as extra property
- Generated README.md contains dataset description in markdown format
- Crawling non-archive files (non zip files) doesn't require downloading (faster crawling)
- Time stamps in datalad logs are configured to be displayed when crawling
- Refactoring code so there is less redundant saving/committing/pushing
#173

Zenodo crawler fixes and improvements

---

scripts/crawl_zenodo.py

Crawler generated file names are now shorter without the entire link's host and path, only filename
Generated DATS.json conforms with validator when license field is missing in Zenodo metadata
#183

Shorter crawled dataset file names

---

.gitmodules

McGill-EMC: RNA-seq experiment from human brain sample.
The RNA-seq experiment from the human brain sample. The donor is 42 years old healthy male individual. Biomaterial type is primary tissue with tissue type Brodmann (1909) area 11.
The dataset contains two bigWig files. The files are located on the FTP server.
The dataset is derived, there is a link for raw data in DATS file but accessing raw data requires filing a request.

Add McGill-EMC: RNA-seq experiment from human brain sample dataset

---

.gitmodules
README.md

This PR replaces the existing refseq dataset with three datasets contained in the directory refseq, each with a name of the format refseq_genus_species.  Each of these datasets contains the relevant data for a given species including _DATS.json, README.md_ and a logo as previously specified. Each submodule also now contains a file called _assembly_summary.txt_ downloaded from the NCBI ftp site, which contains the location and identifier of the most recent release of that genome.  
This structure is designed to work with a perl crawler script which loops through the subdatasets:
- retrieving the current version of the relevant assembly summary from NCBI and determining whether it has been updated;
- if so, retrieve updated versions of the genome FASTA and annotation files, update the …

Restructuring refseq dataset for crawling purposes.

---

.gitmodules

This PR does two things:
1) Temporarily removes the submodule link to the visual-working-memory dataset, as its links are no longer functional and need to be repaired.
2) Updates the submodule link for Khanlab/BigBrainMRICoreg to point at the version after merging https://github.com/conpdatasets/BigBrainMRICoreg/pull/2

Remove non-functional visual-working-memory links and update BigBrainMRICoreg

---

tests/create_tests.py
tests/test_minimal_tests.py

The tests suite currently validates every datasets on each pull request.
The objective of these changes is to perform the minimal amount of test required for futur pull request. Depending on the files a PR modifies it will either (1) run all datatset tests as before, (2) run only a sample of the dataset tests, or (3) none of the dataset tests.
PR #99

Minimal testing of datasets

---

tests/create_tests.py

Fix for the PR #232. The TravisCI environment variable was returning "false" as a string instead of boolean. This led the master build to fail. 
#232

[FIX] Handle TRAVIS_PULL_REQUEST value properly.

---

tests/functions.py

@xlecours pointed out a bug with the current creation of a Datalad provider configuration file; see [logs here](https://travis-ci.org/github/CONP-PCNO/conp-dataset/jobs/672641562#L923). 
This is because the path to the config file does not exist. The brought changes makes sure that the path to the config file exist and overwrite the file if it already exists. The latter is for all authenticated dataset using loris to reuse the same provider config filename.

Fix datalad provider configuration file for authenticated loris datasets

---

tests/functions.py

Currently, the test suite selects files to download in ascending file size. This is problematic when datasets have numerous files since the test timeout. This behaviour is seen [here](https://app.circleci.com/pipelines/github/mathdugre/conp-dataset/133/workflows/e53abd84-2e56-4a34-92eb-bfbd4f766c38/jobs/280/parallel-runs/1?filterBy=FAILED) with the preventad-open dataset. 
The proposed solution is a compromised between finding small enough files for fast download and fast solution to find the files.

Modification of the method for choosing file to download during test.

---

scripts/Crawlers/ZenodoCrawler.py
scripts/unlock.py

Currently, the Zenodo crawler creates a configuration file `unlock.py` for authenticated dataset. To respect the convention, it should be an executable file named `config` with a shebang to indicate the language. 
This followed after a discussion with @glatard

Zenodo config

---

tests/functions.py

Currently, the tests for loris dataset with authentication fail after the first one is ran; see [CircleCI logs](https://app.circleci.com/pipelines/github/CONP-PCNO/conp-dataset/41/workflows/96a8a088-d1e3-4426-ac78-5e49b1262773/jobs/78/tests).  
This change checks if the Datalad provider path already exist before creating it.

FIX for the datalad provider config of loris dataset.

---

scripts/Crawlers/ZenodoCrawler.py

After changing the filename for the dataset pre-configuration in #257, the config file is now put into the annex.
This change will bring back the expected behaviour for the configuration file.

[FIX] Include config in the no-annex files

---

tests/functions.py

The current test do not allow to test the submodules within a dataset; such as [visual-working-memory](https://github.com/conpdatasets/visual-working-memory/tree/7ad5fd7fd950494e5567dc13aa760a5167ba6795) dataset.
Allowing to test a dataset submodules improve the test coverage while preventing some dataset to be skipped during the tests.

Handle test of submodules in dataset

---

.gitmodules

This PR updates` .gitmodules` to point at the copy of `visual-working-memory` on conpdatasets.  The dataset was regenerated to fix download errors last month, but I had been testing that in my own fork and the link was still pointing there.

Updating .gitmodules for visual-working-memory

---

.circleci/config.yml
tests/functions.py

Currently, the configuration use Datalad to install all dataset during the build phase. This is problematic as when a dataset fails to download the whole test suite fails ; as right now.
@glatard proposed to install the dataset individually when needed. This has two main advantages: (1) only tests unable to install via Datalad will fail and (2) it will speedup the test suite when only a sample of test are run as described in #232.

Change to the Circle CI Build configuration

---

tests/functions.py

Currently, some dataset tests fail due to git-annex command failures.
These changes handle those errors.

Handling Git-annex command failure in tests

---

tests/create_tests.py

When a PR is made, the CI script will try to find the minimal number of tests to be performed, however, there is a problem with the implementation for finding to which datasets modified files are part of.
These changes solve this issue.
That issue was found in #286.

Fix pattern lookup for minimal testing

---

tests/functions.py

The refactoring of the function in #285 broke the calculation of the annexed files size.
This change fixes this issue.

Fix calculation of size of annexed files

---

scripts/unlock.py

This change allows the crawler unlock script to run from anywhere. This is useful when someone when to run it from a dataset root.

Modify script to unlock authenticated dataset with Zenodo

---

scripts/Crawlers/BaseCrawler.py
scripts/Crawlers/OSFCrawler.py
scripts/Crawlers/ZenodoCrawler.py
scripts/crawl.py
scripts/crawl.sh

- When crawling datasets from Zenodo, when the crawler detects the presence of a contributor of the type "Project Leader", it will map it to the role "Principal Investigator" in the DATS.json file. It only allows the role of Principal Investigator for one creator for the entire list of creators
- OSF crawler now adds total file size, unit and number in generated DATS file
- OSF crawler now adds homepage link in DATS file
https://github.com/CONP-PCNO/conp-portal/issues/254

Crawler bug fixes and feature additions

---

tests/create_tests.py

When deprecating TravisCI in #307, a bug was introduced for the detection of files on new PRs. This is seen the CircleCI logs [here](https://app.circleci.com/pipelines/github/CONP-PCNO/conp-dataset/199/workflows/66f3437a-ae27-46f7-80b5-2578830b2d83/jobs/365/steps).
This change is to fix the bug.

[FIX] pull_number was undefined.

---

.circleci/config.yml

This allows to use the _conp-dataset_ image user usage; such as local testing and latest
version of the environment required to install (or create) datasets.
#9 addresses a use case for this change.

[REFACTOR] Renamed the Docker image used by CircleCI.

---

tests/template.py

This is following some inconsistency to verify the file system integrity when the
dataset contains metadata #303 .
fix #303

FSCK ignore dataset metadata

---

.gitmodules

This is the umbrella dataset of the Courtois Neuromod project, available [here](https://github.com/courtois-neuromod/cneuromod). The sub-datasets `anat`, `movie10`, `hcptrt` and `friends` are not public yet, but it should be quite easy to add them when they are. Dataset was already a DataLad repository, only a DATS file was required.
- [ x ] Dataset can be installed using DataLad, recursively if it has sub-datasets
- [ x ] Every data file has a URL
- [ x ] Every data file can be retrieved or requires authentication
- [ x ] `DATS.json` is a valid DATs model

[WIP] Added cneuromod umbrella dataset

---

scripts/dats_validator/README.md
scripts/dats_validator/examples/invalid_dats.json
scripts/dats_validator/examples/valid_dats.json
scripts/dats_validator/validator.py
tests/test_dats_validator.py

Addresses issue #345 
- Validates that `extraProperties` contains categories `subjects`, `files ` and `CONP_status` in dataset and all nested datasets
- Validates that `CONP_status` values are `CONP`, `Canadian`, `external`
Now the validation will be split into two parts:
1. Validates DATS.json against dataset_schema.json
2. Validates if all required extra properties are present in DATS.json and have valid values (according to this: https://github.com/CONP-PCNO/conp-documentation/blob/master/CONP_DATS_fields.md)
Whenever the controlled vocabulary (e.g. for CONP_status) changed, or new required `extraProperties` are added, these changes should go to REQUIRED_EXTRA_PROPERTIES.
@glatard @joeyzhou98 Could you please add `validate_non_schema_required` to tests, the same as it was done with …

Add validation of required extra properties and their values

---

.circleci/config.yml
tests/test_dats_validator.py
tests/test_osf_crawler.py
tests/test_zenodo_crawler.py

* Added `__init__.py` files in directories from where files are imported
* Added `scripts` to the PYTHONPATH
* Fixed path in dats_validator.py
* Removed deprecated (now removed) use of datalad.api.add (breaks in 0.13.1)
Not sure what triggered the breaking of the tests, most likely the datalad update.

Fixed circleci tests

---

.gitmodules

Add Braincode **Mouse Image** dataset. This is the first out of three main datasets from OBI.
Contains 26 children datasets in `hasPart`.
#353

Add Braincode Mouse Image dataset

---

.gitmodules

This adds the Cuban Human Brain Mapping Project (CHBMP) to the CONP super dataset.
Note: the subproject CHBMP has no data yet in the repository, just descriptions of the dataset
Resubmitted https://github.com/CONP-PCNO/conp-dataset/pull/369

Added CHBMP dataset as a submodule

---

.gitmodules

Add Braincode fBIRN Image dataset. This is the second out of three main datasets from OBI.
Contains 13 children datasets in `hasPart`.
#353

Add Braincode fBIRN dataset

---

scripts/Crawlers/ZenodoCrawler.py

This fixes a bug encountered by crawling the dataset mentioned in the following issue: https://github.com/CONP-PCNO/conp-dataset/issues/432.
In Zenodo, a concept DOI is attributed to a dataset upon the creation of a dataset with no pre-existent DOI associated with it. Here is how the Zenodo DOI works:
- if a user does not specify a DOI at the time of a dataset upload on the Zenodo platform, Zenodo will create a "Concept DOI" and a "version DOI". The Concept DOI represents the dataset and all its associated versions.
- if a user specifies a DOI at the time of the upload, Zenodo will not create new DOIs (neither concept DOI or version DOI) and it will use the specified DOI the user gave instead.
In the case of the mentioned dataset above, the DOI was a Frontiers in Neuroscience DOI, …

Fix Zenodo crawler for datasets with no concept DOI

---

scripts/requirements.txt

This adds a `requirements.txt` file for the crawler pipeline.
Once merged, users will only need to execute `pip install -r requirements.txt` to get all the requirements installed before running the crawler.

Add the requirements.txt file for the crawler

---

scripts/Crawlers/ZenodoCrawler.py

Zenodo does not allow for JSON files to be uploaded for a dataset. To circumvent this, we will tell users to upload a DATS file without the .json extension to their Zenodo dataset. The changes in this PR adds the renaming of a DATS file into DATS.json if a DATS file exists.
https://github.com/CONP-PCNO/conp-dats-editor/issues/3

Rename downloaded DATS file from Zenodo into DATS.json

---

scripts/crawl.py

This modifies the code of the crawler so that the conp-dataset path can be configured and not hardcoded.
In `.conp_crawler_config.json`, the following needs to be added to the config file:
```
"conp-dataset_path": "PATH TO THE conp-dataset DIRECTORY",
```
Then the scripts will load the ZenodoCrawler and OSFCrawler libraries based on that path.
NOTE: this config has already been added to the `.conp_crawler_config.json` file of `conp-bot@zenodo-crawl.acelab.ca`

Make the conp-dataset PATH configurable for the crawlers

---

scripts/Crawlers/OSFCrawler.py
scripts/Crawlers/ZenodoCrawler.py

Some datasets will provide their own `DATS.json` and `README.md` files in Zenodo or OSF. This PR modifies the crawler so that instead of indexing those two files, it will instead download them so later on they can be read by the validator.
Note: I also removed the patch I issued last week to rename `DATS` to `DATS.json` since Zenodo now supports `.json` file uploads.

Modifies the crawlers to download DATS.json and README.md files instead of annexing them if they are present in the uploaded dataset

---

scripts/Crawlers/OSFCrawler.py

Currently, the OSF crawler only supports crawling files that are stored in `osfstorage` data provider. However some datasets might have files in other types of data provider (for example `github`). 
The changes allow the support of crawling files from multiple data providers and therefore modify the way the OSF datasets will be organized in `conp-dataset`:
```
__ conp-dataset-Multimodal-data-with-wide-field-GCaMP-imaging
|__ .datalad/
|__ Part_1/
|__ Part_2/
|__ .conp-osf-crawler.json
|__ .gitattributes
|__ DATS.json
|__ README.md
```
to 
```
__ conp-dataset-Multimodal-data-with-wide-field-GCaMP-imaging
|__ .datalad/
|__ osfstorage/
|__ Part_1/
|__ Part_2/
|__ .conp-osf-crawler.json
|__ .gitattributes
|__ DATS.json
|__ README.md
```
Should resolve: …

Download OSF files from all storage type instead of just osfstorage

---

scripts/Crawlers/BaseCrawler.py

In the case the dataset is updated, the README.md file is not recreated. I missed that part yesterday when I refactored the crawler so that it could use the DATS.json and README.md uploaded by users through Zenodo or OSF.
This fixes it and add the creation of README.md file if a dataset is updated (note: this is done by default for new datasets).
This should fix the current issue with PR #448

Recreate README.md if it does not exist

---

scripts/Crawlers/OSFCrawler.py

OSF supports multiple data providers. In the case of Github data provider (and probably all non-OSF Storage data provider), the file size information is not available in the API response. This causes the crawler to crash with the following error:
```
Traceback (most recent call last):
File "./scripts/crawl.py", line 84, in <module>
OSFCrawlerObj.run()
File "/data/crawler/conp-dataset/scripts/Crawlers/BaseCrawler.py", line 254, in run
self.add_new_dataset(dataset_description, dataset_dir)
File "/data/crawler/conp-dataset/scripts/Crawlers/OSFCrawler.py", line 207, in add_new_dataset
dataset_size, dataset_unit = humanize.naturalsize(sum(dataset_size)).split(" ")
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```
The proposed fix will compute the file_size using the `git …

[OSF crawler] Get the size of annexed files from git-annex info if it is not present in the OSF API response

---

scripts/Crawlers/BaseCrawler.py

Github is deprecating the API authentication through query parameters. Instead, they recommend users move the authentication in the header of the request.
This PR modifies our crawler to use authentication in the header of the request.
See Github documentation: https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/

[Crawler] Resolves the deprecation notice regarding Github token in URL

---

.gitmodules

This will add the preventad-registered dataset to the conp-dataset. 
NOTE: a DOI will be created on Monday upon the official release of PREVENT-AD registered and this PR will be updated with the correct DOI once we have it.

Adding preventad-registered to the conp-dataset super dataset

---

scripts/dats_validator/examples/invalid_dats.json
scripts/dats_validator/requirements.txt
scripts/dats_validator/validator.py

The PR addresses the extraProperties category `derivedFrom` validation.
- The code validates `derivedFrom`  value which is expected to be a valid url: sends request and checks if the response status code is 200.
- The code is not bounded to the GitHub API because I assume we might have cases when the `derivedFrom` points to the dataset persistent identifiers on other data portals or doi.org.
- To avoid redundant calls response statuses are stored in in-memory cache dict.
#436

Add derivedFrom validation

---

scripts/Crawlers/ZenodoCrawler.py

This adds the date created and date updated of Zenodo datasets to the automatically generated DATS.json file from the Zenodo crawler.
#375 
Documentation of the API endpoints can be found here: CONP-PCNO/conp-documentation#49

[Zenodo crawler] Add date created and date modified to the DATS file

---

scripts/Crawlers/ZenodoCrawler.py

This fixes the call to the dictionary that stores the created and updated keys in the Zenodo API response.

[Zenodo crawler] Fix dictionary where the created and updated keys are stored in the Zenodo API response

---

.gitmodules

At a meeting the morning December 18 2020, it was decided that the example data stored in https://github.com/conp-bot/conp-dataset-Expression-based-polygenic-score-from-the-amygdala-5HTT-gene-network/ was more appropriately added as an auxiliary to https://github.com/SilveiraLab/ePRS and made available along with pipelines, so this PR removes that dataset from https://github.com/CONP-PCNO/conp-dataset.

removing expression-based polygenic risk score dataset from CONP data interface.

---

scripts/dats_validator/requirements.txt
scripts/dats_validator/validator.py

The PR adds URI format validation to dats validator script.
**Example:** distribution->access->landingPage has a type `string` and format set to `uri`.
If the provided URI  is not of a valid format it will throw an error.
**Important:** e.g. `www.internationalgenome.org` is not a valid URI.
URI must start with a naming schema (e.g.: `http:`, `urn:`, `mailto:` etc.).

Add URI format validation

---

.gitmodules

This PR updates `conp-dataset/projects` to remove and reinstall the `calgary-campinas` submodule in the hope of fixing odd behaviour with `.git` folders that was preventing it from showing in the CONP portal interface.

updating calgary-campinas submodule

---

scripts/data_aggregation_summary_scripts/create_dataset_statistcs_per_data_providers.py
scripts/data_aggregation_summary_scripts/create_statistcs_per_data_providers.py
scripts/data_aggregation_summary_scripts/create_tools_statistics_per_domain.py
scripts/data_aggregation_summary_scripts/lib/Utility.py
scripts/data_aggregation_summary_scripts/lib/__init__.py

This adds a new set of tools to automatically create summary for reporting. These tools return CSV files.
- `create_dataset_statistics_per_data_providers.py`: creates summary statistics (number of datasets, number of files, dataset keywords, dataset size) per data provider (Zenodo, OSF, LORIS, BrainCode...).
- `create_tools_statistics_per_domain.py`: creates a summary statistics (number of tools, containers, execution capacity) per domain of application (neuroinformatics, bioinformatics, MRI, EEG, Connectome, BIDS-App...)

Create additional summary scripts

---

scripts/Crawlers/OSFCrawler.py

This adds the following metadata to the automatically generated DATS.json from the OSF crawler:
- origin_institution (when there are institutions associated to the dataset in the OSF API response)
- identifier and identifier source (when there is a DOI associated to the dataset in the OSF API response
- date created
- date modified
When an identifier is present, it is also added to the end of the README file.
Documentation of the API endpoints can be found here: https://github.com/CONP-PCNO/conp-documentation/pull/49
Related issue: #375

[OSF crawler] Add more OSF metadata to DATS.json and README for the OSF crawler

---

scripts/Crawlers/OSFCrawler.py

This modifies the OSF crawler to support components. 
- When a dataset contains OSF components (example: https://osf.io/xhvsk/), then the content of the components will be crawled along with the other files from the dataset.
- For datasets that have a parent key in the API response (a.k.a. the dataset is a component of another OSF dataset), the crawler will skip that dataset since its content is going to be part of the parent dataset linked.
Notes:
- #477 conp-bot PR is the result of the crawler modifications present in the PR
- #405 and #406 were two earlier PRs for components dataset. Since the files are now in #477, those two PRs have been closed.
https://github.com/CONP-PCNO/conp-dataset/issues/419

Handling OSF components

---

scripts/Crawlers/ZenodoCrawler.py

This fixes a bug in the Zenodo crawler where next pages of results to the Zenodo API query were not considered.
#495

Loop through next pages to get the whole list of Zenodo datasets

---

scripts/dats_validator/examples/invalid_dats.json
scripts/dats_validator/examples/valid_dats.json
scripts/dats_validator/validator.py
tests/template.py
tests/test_dats_validator.py

In order to harmonize DATS between datasets, a review of the available content for the distributions.formats field has been done and the following convention were determined:
file format should be capitalized without the dot preceding the format (exceptions being BigWig, NIfTI and RNA-Seq)
Examples of invalid format: tsv, .txt...
Examples of a valid format: TSV, TXT, MINC...
#491
Note: this is the same changes as in https://github.com/CONP-PCNO/conp-dataset/pull/498 but had to resubmit the PR as I pushed some dataset changes that should not have been in the PR modifying the validator and the tests...

Modifies validator to flag unusual values for the DATS 'formats' field

---

scripts/Crawlers/ZenodoCrawler.py

The date type of the DATS file created by the Zenodo crawler are `Date Created` and `Date Modified`. This changes those strings to comply with lower case convention, ergo `date created` and `date modified` so that the crawler creates valid DATS files.
#519, #499

Fix encoding of date type to be all lower case for the DATS file

---

scripts/datalad_helper_scripts/batch_remove_deprecated_URLs.py

This adds a script that allows the removal of certain URLs from a DataLad dataset.
Example: before running the script:
```
git annex whereis full16_1000um_optbal.mnc 
whereis full16_1000um_optbal.mnc (1 copy) 
00000000-0000-0000-0000-000000000001 -- web
web: ftp://bigbrain.loris.ca/BigBrainRelease.2015/3D_Volumes/Histological_Space/full16_1000um_optbal.mnc
web: ftp://bigbrain.loris.ca/BigBrainRelease.2015/3D_Volumes/Histological_Space/mnc/full16_1000um_optbal.mnc
```
The first URL under web is not valid anymore and needs to be removed. The script attached allows to remove URLs that matches what given as input:
```
python batch_remove_deprecated_URLs.py -d /Users/cmadjar/tmp_BigBrain/bigbrain-datalad -u Histological_Space/full -c -v
```
Option `-d` takes in the full path to the DataLad …

Add a script that can remove specific URLs from the DataLad remote

---

scripts/dats_validator/examples/invalid_dats.json
scripts/dats_validator/examples/valid_dats.json
scripts/dats_validator/validator.py
tests/template.py

As an exercise towards DATS value harmonisation, the dates type have been harmonized to be all lower case with the exception of "CONP DATS fileset creation date".
This PR adds some functions to the validator and the automated tests to validate that the date type is indeed all lower case.
Note: since the DATS GUI is only suggesting to add dates to the dataset_schema.json and the primaryPublications section of the DATS file, the validation will only check those for now.
#499

Add validation of date type to the validator and the tests

---

.github/dependabot.yml
.github/workflows/docker_build.yml

The current GitHub action for building and pushing the repo image to DockerHub is failing.
This is because the action uses a deprecated version of the `docker/build-push-action`.
This PR aims at updates the version for the docker action using the [current recommended approach](https://github.com/docker/build-push-action#git-context).
To be functional, this PR requires secrets for:

[FIX] Docker workflow

---

.github/dependabot.yml

It looks like I introduced a syntax error in one of the GitHub actions in #528.

[FIX] syntax error was introduced.

---

scripts/crawl.py
scripts/crawl.sh

Currently, in `crawl.sh`, if the command `git pull --no-edit main master` fails, the touchfile is never removed and the crawler will never execute since it will always see that the touchfile is present until someone manually removes it
`git pull` failling:
Crawler never starting again:
Only continue executing script if that command passes and handle creation and deletion of the touchfile in the shell script instead of letting the python script handle the deletion of the touchfile since the python script might not execute.
Also redirecting output of `git pull` to the logfile for easier debugging and allow for overriding the `BASEDIR` environment variable which is the path to the `conp-dataset` repo directory where the crawler does its job to allow other instances of the script to run in …

Handle crawler git pull errors

---

tests/functions.py

This PR fixes the reported file size when testing the download of a file fails.
Currently, the test always show _inf_ . Moreover, this PR brings human format to the file size for easier readability.

[FIX] Wrong file size reported when a download fails.

---

tests/functions.py
tests/requirements.txt
tests/template.py

This PR aims at solving timeouts of archived datasets.
Two changes are introduced:
1. When getting files for download, those not part of an archive are prioritized.
2. Before downloading files, the test will now estimate a download time base on the file to download. i.e. Either normal file or archived ones. Note: The download time is capped at 10 minutes to avoid lengthy test.
fix #554

Fix timeout of archived datasets in the testing suite

---

.github/workflows/stale.yml

This PR aims to simplify the maintenance of issues and PRs.
The GitHub workflow proposed will automatically label issues and PRs as **stale** after a configured time. If no actions is taken after a set number of days, that issue/pr will be closed automatically.
- Issues:
- label stale: 30 days
- close after labeling: 5 days
- Pull requests:
- label stale: 45 days
- close after labeling: 10 days

[ADD] Automatically label/close stale issues and pull requests.

---

.circleci/config.yml
.circleci/images/Dockerfile

This PR aims at bumping the Python version to 3.9 in CircleCI.
It was discussed in #577 that the python typing module went through a lot of changes in the recent version.
Upgrading the Python version used for the development of the test suite would result in better readability and maintenance; see [PEP 585](https://www.python.org/dev/peps/pep-0585/).

[MODIFY] Bump Python version to 3.9 in CircleCI.

---

.circleci/config.yml

Bumping the Python version in #583 broke the CircleCI cache.
Pip seems to find the package form the previous Python version thus skip the install and leaving the current Python version with no installed module.
Bump the cache key in the CircleCI configuration.
Origin of the issue: #583

[FIX] Clear CircleCI cache by bumping the key version.

---

.gitmodules
.pre-commit-config.yaml
scripts/dats_validator/requirements.txt
scripts/dats_validator/validator.py
scripts/requirements.txt
tests/requirements.txt
tests/test_dats_validator.py

The current pre-commit config as some hook conflicting with each other.
This PR solves this issue by re-ordering the hooks in a non-conflicting way. This was tested by using a previous version of the repo (cab6b33dc9fdfdf2adf39fcecdc7b619baf8a13) and running the new configuration on it. The files auto-formatted now pass on the second execution.
Additionally this PR temporarily disable `mypy` and `pydocstyle` hooks while the code does not abide their rules yet. This in done in order to have the linting workflow succeed PRs.
#572 points out the issues with the current configuration.

Remove and Reorder pre-commit hooks

---

scripts/Crawlers/BaseCrawler.py
scripts/Crawlers/ZenodoCrawler.py
tests/test_zenodo_crawler.py

We used to crawl private datasets on Zenodo by appending the dataset token in the URL which leaks it to the public in the git annex history. Now we use bearer token to authenticate via `DATALAD_ZENODO_token` environment variable which is more secure since it doesn't leak the token in the commit history

Zenodo crawler private dataset refactor

---

.circleci/config.yml

Currently, only the `scripts/dats_validator/conp-dats` sub-modules is installed during the build phase of the tests.
#640 demonstrates the issue with this approach.
This PR proposed to recursively install the `scripts` directory during the build phases. This should avoid further failure in the future when adding more sub-modules.

[FIX] CircleCI config to allow sub-modules installation in the build phase

---

tests/functions.py

This PR fix the authentication method for Zenodo restricted datasets in the test suite.
It takes the current `${DATASET}_ZENODO_TOKEN` secret and sets it to the expected `DATALAD_ZENODO_token` environment variable.
#601

[FIX] Authentication for Zenodo datasets.

---

Dockerfile

The workflow for building a Docker image is currently failing.
The issue is caused by the new way Ubuntu installs pip3. It nows create a symlink to pip which conflicts with the current Dockerfile.
This PR remove the manual symlink from pip3 -> pip and feeze the version of Ubuntu to avoid further  unexpected failures.

[FIX] docker build workflow failed due to changes in pip installation.

---

scripts/auto_archive.py

This PR fix a bug introduced in #675 where the archives are not stored in the right location.

[FIX] archives were stored in the wrong location.

---

scripts/auto_archive.py

This PR modify the auto archiving script to only update the submodules under the `/projects` path; i.e. datasets.

[MODIFY] Only consider submodule as part of the /projects folder.

---

tests/template.py

In PR #697, several datasets that were crawled by OSF or Zenodo failed the tests after updating the conp-dats submodule. This PR should be able to fix the issues flagged by the tests for the retrospective OSF datasets that do not have a distribution->formats field.
Suggestion was to completely skip the DATS tests for those retrospective datasets until we get a chance to contact the authors of the datasets so that their DATS files can be fixed.

Test to see if that fixes the test failure reported in 697

---

scripts/auto_archive.py
scripts/datalad_utils.py

Because some datasets to archive are actually quite large, disk space gets quickly filled up. Once an archive is created, the auto-archive script will uninstall the DataLad dataset that has been archive to manage space better on the server.
Note: initially tried with `datalad drop` but realized quickly that it did not really free up space on the server so instead, we have to run `datalad uninstall`. See https://github.com/datalad/datalad/issues/6009 created on the DataLad GitHub repo.

Uninstall a dataset once the archive has been created

---

scripts/Crawlers/ZenodoCrawler.py
scripts/dats_validator/validator.py

This modifies the Zenodo crawler in order to fetch the `subjects` information present for a dataset API response and insert them into the `isAbout` field of the automatically generated `DATS.json` file.
Example of the what a DATS `isAbout` would look like once automatically generated:
```
"isAbout": [
{
"identifier": {
"identifier": "http://uri.interlex.org/base/ilx_0106458"
},    
"name": "Magnetic resonance imaging"
},        
{
"identifier": {
"identifier": "http://uri.interlex.org/base/ilx_0110407"
}, 
"name": "Schizophrenia"
}
],
```
Note: the validator needed a quick fix as well to not crash on such DATS files.
Resolves #677

Add 'subjects' metadata from Zenodo API to 'isAbout' field in DATS model

---

scripts/Crawlers/BaseCrawler.py

This modifies the base crawler pipeline to read the DATS.json file of the crawled dataset and check whether there is an 'derivedFrom' entry in the extra properties. If there is one, then add the source dataset as a submodule to the crawled dataset.
#701

If derivedFrom field is populated in DATS file, automatically add the raw dataset to the datalad repo

---

tests/test_dats_annotator.py

The CONP DATS schema is used as a submodule for the DATS annotator. This PR updates the submodule in order to include the recent schema extensions. A test fixture also had to be updated to match the updated schema.
This came up in #708

Update the DATS context submodule

---

.gitmodules

This PR updates the `DATS.json` file in the `MICA-MICS` dataset to connect to a local copy of their logo. [ Replacing previous content that was garbled by an error in branch management. ]

updating MICA-MICS logo

---

scripts/auto_archive.py

This fixes the following error when reading the date the archiver was last executed from .conp-archive:
```
Traceback (most recent call last):
File "/data/conp-dataset/./scripts/auto_archive.py", line 179, in <module>
modified_datasets = get_modified_datasets()
File "/data/conp-dataset/./scripts/auto_archive.py", line 102, in get_modified_datasets
since = datetime.fromisoformat(fin.read())
ValueError: Invalid isoformat string: '2022-03-01T14:56:46.961875-04:00\n'
```

Remove trailing \n from the date read from .conp-archive

---

tests/template.py

This modifies the tests template to add a test for submodules of derived datasets to ensure they are at the latest commit version.
Resolves https://github.com/CONP-PCNO/conp-dataset/issues/763

Update the tests to add a check for dataset's submodule commit versions

---

.gitmodules

This PR replaces https://github.com/CONP-PCNO/conp-dataset/pull/717, linking to a local copy of the dataset rather than the source repository.

Adding new MouseBytes dataset

---

.gitmodules

This PR adds the https://github.com/conpdatasets/braincode_Epilepsy_Priority_Setting_Partnership dataset to conp-dataset.

adding braincode epilepsy dataset

---

.gitmodules

This PR replaces #807, adding two new braincode datasets, `braincode_EpLink` and `braincode_CP_NET`.

Add braincode_EpLink and braincode_CP_NET datasets

---

.pre-commit-config.yaml
scripts/conp_to_nidm_terms/template.jsonld
scripts/dats_jsonld_annotator/annotator.py
tests/functions.py
tests/test_dats_annotator.py

The "pre-commit hooks" GitHub action fails because the flake8 pre-commit hook is misspecified. This fixes that issue and incorporates the results of `pre-commit run --all-files`, and a minor change to the json-ld annotator, making the exception raised slightly more specific to satisfy flake8.

Fix pre commit

---

.pre-commit-config.yaml

This is a first attempt at solving #782. The pre-commit config is the only place I could find that checks for a newline at EOF, and I couldn't find a mechanism for the pre-commit to apply to subdatasets, so I'm not really confident that this will have the intended effect for subdatasets.
I have verified that it works for the root dataset, and if someone could point me at an instance of this issue causing problems, I could double check that this will work in that case.

Allow missing newline at EOF for git config files

---

.gitmodules
scripts/sftp-crawler.pl

This PR replaces the previous `Taowu` dataset, which had been giving download failures, with `Taowu_local`, the same content hosted on `sftp.conp.ca`.  It also adds an updated version of the crawling script `sftp-crawler.pl` to the `scripts` directory.

Add updated copy of Taowu dataset hosted at sftp.conp.ca

---

.gitmodules

This PR adds the CONNECT concussion project's RECOVER dataset, Braincode data release DR-14.

Adding new Braincode concussion dataset

---

.gitmodules

This PR removes the cbig-parkinsons dataset from the live server pending corrections and expansions planned by the source research group.

Removed CBIG Parkinsons dataset

---

.gitmodules

In this PR, the AdolescentBrainDevelopment subdataset has been removed and then re-added as a submodule with the `main` branch explicitly specified, to test whether this resolves the problem with `git checkout` default expecting updates on the `master` branch and not transferring them from the CONP-PCNO github repository to the live server when a `main' branch is involved.

Test specifying branch in .gitmodules to address problem with transfer to live server

---

.gitmodules

This PR updates the cbig-als DATS.json file with a new field, extraProperties=>registrationPage.  It also changes the .gitmodules specification of this dataset, adding `branch=main` to address the issue of transfer to the portal.

Updating DATS.json for cbig-als with test registrationPage property

---

.gitmodules

This PR removes submodules containing the six openpain datasets, as these have been non-functional at the data provider end for some time and there has been no indication that this situation will be repaired, and also the three NCBI reference genomes as they were proof-of-concept datasets from the beginning of the CONP project with little ongoing utility.

removing openpain and refseq submodules

---

.gitmodules

This PR removes the recently added `Semantic_Encoding_Memory_Task` dataset as a stopgap measure to address a Datalad installation problem apparently caused by concatenated lists of dataset names exceeding a length threshold.  This will fix the download functionality short-term.

temporary fix: removing Semantic_Encoding_Memory_Task

---

.gitmodules

https://github.com/CONP-PCNO/conp-dataset/pull/923 added the new submodule link in `.gitmodules` after the linter-mandated terminal CR/LF rather than before, and this PR corrects that, against the possibility of this causing problems parsing the file subsequently.

removing superfluous blank line from .gitmodules

---

.gitmodules

This PR escapes a single-quote in the `description` field in the DATS.json file in the `eegnet_mfa` dataset, which was being erroneously read as an SQL field terminator during the archiving process.

correcting description in eegnet_mfa DATS.json

---

.gitmodules

Automatic addition of a new dataset crawled by conp-bot in https://github.com/CONP-PCNO/conp-dataset/pull/958 still fails with a malformed submodule link in `.gitmodules`, causing download of the entire conp-dataset to fail.  This PR removes the malformed link and manually adds the new dataset instead.

Updating link to test conp-dataset submodule

---

.gitmodules

This PR re-adds the "Paper is not enough" dataset originally added in https://github.com/CONP-PCNO/conp-dataset/pull/958 to test whether the changes in https://github.com/CONP-PCNO/conp-portal/pull/700 have fixed the issue with updates to CONP-PCNO/conp-dataset not filtering through to appear on https://portal.conp.ca/.

manually adding another Zenodo dataset to test recent portal changes.

---

.gitmodules

This PR removes the previous version of the `conp-dataset-Paper-is-not-enough-Crowdsourcing-the-T-sub-1-sub-mapping-common-ground-via-the-ISM` subdataset, which had been manually added as a workaround for conp-bot crawler problems, so that we can cleanly test the automated retrieval of this dataset in https://github.com/CONP-PCNO/conp-dataset/pull/993.

removed manual test conp-bot load

---

.gitmodules

This PR removes the manually added version of  `/conp-dataset-Quantitative-T1-MRI/`, as now that the crawler works again a correctly retrieved crawled version will be added by https://github.com/CONP-PCNO/conp-dataset/pull/998.

Removed another obsolete manually-added crawler dataset

---

scripts/Crawlers/BaseCrawler.py
scripts/Crawlers/ZenodoCrawler.py

- adds required ExtraProperties:
```
{
"category": "CONP_status",
"values": [
{
"value": "Canadian"
}
]
},
{
"category": "subjects",
"values": [
{
"value": "unknown"
}
]
}
```
- fix a Zenodo API change breaking the landingPage population 
- fix the types format.

Fix zenodo crawler to comply with dats validation

---

.gitmodules

This PR removes three lines from the `.gitmodules` file referring to a dataset that was not added correctly.

Updating .gitmodules to remove misplaced lines referring to RISE subdataset

---

.gitmodules

This PR removes the former `eegnet_face13` repository and adds a new `eegnet_fac` repository in its place; this was done because the existing `eegnet_face13` at the data provider's end was a fork of another dataset, which was causing some collisions with apparent duplicates.  The data content of the two repositories is identical apart from updating the `landingPage` field in DATS,json, as was done for other EEGnet datasets in #1042, but the repository history is now independent and should no longer cause clashes.

replacing eegnet_face13 subdataset with updated eegnet_fac repository
